readme: Remove outdated reference to homebrew cask (fixes #100)
As of right now:

$ brew cask install syncthing-app
Error: Cask 'syncthing-app' is unavailable: No Cask with this name exists.